source 'https://Jasperav@bitbucket.org/Jasperav/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, ’11.0’

use_frameworks!
target 'JVTimeable_Tests' do
  pod 'JVTimeable', :path => '../'
  
  
end
